// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX_YEVIDsDF0NA4QPUrD9isjAX1XFwRXU',
    appId: '1:619374604919:web:07df4da2064c74e2dd0c72',
    messagingSenderId: '619374604919',
    projectId: 'spothome-a94bf',
    authDomain: 'spothome-a94bf.firebaseapp.com',
    storageBucket: 'spothome-a94bf.appspot.com',
    measurementId: 'G-PJ4T5P7H8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpxBu-bywRnPKocTB3ML22TgdhhyZ9m9Y',
    appId: '1:619374604919:android:6ffed2d76207a511dd0c72',
    messagingSenderId: '619374604919',
    projectId: 'spothome-a94bf',
    storageBucket: 'spothome-a94bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWkc-3gLFYlC7e0xoNQnRdSwW_2um3veQ',
    appId: '1:619374604919:ios:97bad8c8be9ed046dd0c72',
    messagingSenderId: '619374604919',
    projectId: 'spothome-a94bf',
    storageBucket: 'spothome-a94bf.appspot.com',
    iosBundleId: 'com.example.spotHomee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWkc-3gLFYlC7e0xoNQnRdSwW_2um3veQ',
    appId: '1:619374604919:ios:97bad8c8be9ed046dd0c72',
    messagingSenderId: '619374604919',
    projectId: 'spothome-a94bf',
    storageBucket: 'spothome-a94bf.appspot.com',
    iosBundleId: 'com.example.spotHomee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX_YEVIDsDF0NA4QPUrD9isjAX1XFwRXU',
    appId: '1:619374604919:web:3f585673ba0e0e09dd0c72',
    messagingSenderId: '619374604919',
    projectId: 'spothome-a94bf',
    authDomain: 'spothome-a94bf.firebaseapp.com',
    storageBucket: 'spothome-a94bf.appspot.com',
    measurementId: 'G-DKGY2012DR',
  );
}
